### ISSUE TITLE
getoutput: Can't convert 'list' object to str implicitly

### ISSUE THREAD

**Issue by Henry-White** [peppelinux/xt_recent_parser#1]
Hi,
Thanks for your job. Very useful script. But unfortunately I cant run it on Python 3.2.3.
I nave no skills in python. Had tried to replace subprocess.getoutput with another functions without success. Any advices? Thanks.

/home/admin# python3 xt_recent_parser.py
Traceback (most recent call last):
  File "xt_recent_parser.py", line 32, in <module>
    _kernel_config_path = '/boot/config-'+subprocess.getoutput(['uname -r'])
  File "/usr/lib/python3.2/subprocess.py", line 635, in getoutput
    return getstatusoutput(cmd)[1]
  File "/usr/lib/python3.2/subprocess.py", line 617, in getstatusoutput
    pipe = os.popen('{ ' + cmd + '; } 2>&1', 'r')
TypeError: Can't convert 'list' object to str implicitly

**Comment by peppelinux** [comment]
I suggest you to use python 3.5 or 3.6.
If you cannot do that and only need help to get it working on python 3.2 I can help you, but I won't fix the code to get it working with a deprecated python version. I hope you can understand

**Comment by Henry-White** [comment]
I appreciated for the fast respond and the offer to help. If this problem is not an issue for anyone, except me, please, don't spend your time on this. Actually, I had made a bash script for this task already.
Thanks a lot again and good luck.
